name: front_is
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.3


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/perfil.png
    - assets/images/git.png
    - assets/images/ingredientes/img_0.png
    - assets/images/ingredientes/img_1.png
    - assets/images/ingredientes/img_2.png
    - assets/images/ingredientes/img_3.png
    - assets/images/ingredientes/img_4.png
    - assets/images/ingredientes/img_5.png
    - assets/images/ingredientes/img_6.png
    - assets/images/ingredientes/img_7.png
    - assets/images/ingredientes/img_8.png
    - assets/images/ingredientes/img_9.png
    - assets/images/ingredientes/img_10.png
    - assets/images/ingredientes/img_11.png
    - assets/images/ingredientes/img_12.png
    - assets/images/ingredientes/img_13.png
    - assets/images/ingredientes/img_14.png
    - assets/images/ingredientes/img_15.png
    - assets/images/ingredientes/img_16.png
    - assets/images/ingredientes/img_17.png
    - assets/images/ingredientes/img_18.png
    - assets/images/ingredientes/img_19.png
    - assets/images/ingredientes/img_20.png
    - assets/images/ingredientes/img_21.png
    - assets/images/ingredientes/img_22.png
    - assets/images/ingredientes/img_23.png